title: <p align="center"> Aloke Kumar Mukherjee </p>
logo: /assets/img/Aloke_Image.png
description: 
<p align="center">
#  <a href="pdf/resume.pdf">Resume</a> |
#  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
#  <a href="https://github.com/sajankedia">GitHub</a>
<BR>
I have 16+ years of experience in ASIC Low Power Analysis, Synthesis, Equivalence Checking and CAD automation in chip design field
</BR>
</p>
#show_downloads: false
#google_analytics:
#theme: jekyll-theme-minimal
